### ISSUE TITLE
manifest for naimkabir/semantic-mediawiki:latest not found: manifest unknown: manifest unknown

### ISSUE THREAD

**Issue by ardref** [NaimKabir/semantic-mediawiki#3] opened 2022-02-01 17:22 UTC
![Screenshot from 2022-02-01 17-18-35](https://user-images.githubusercontent.com/75689892/152017843-c1bda2a3-3364-49e5-95b2-ffc320528148.png)

Ubuntu 20.04.2 LTS

**Comment by NaimKabir** [comment] 2022-02-12 08:18
@ardref Hi, this should work with:

`docker pull naimkabir/semantic-mediawiki:3.2.3` 

To get you unblocked for now. If it's idiomatic to pull docker images without tags, I'll see how I can deploy the latest versions without a tag qualifier.

Let me know if this solves your issue! (And thank your for your patience).

**Comment by NaimKabir** [comment] 2022-02-12 08:54
`docker pull naimkabir/semantic-mediawiki` should now also work!

Once you confirm I'll close this issue. Thanks for flagging this problem!

**Comment by NaimKabir** [comment] 2022-02-16 06:15
@ardref I'll close this for now, but feel free to open if the problem is persistent for you.

**Closed as completed by NaimKabir** 2022-02-16 06:15 UTC

**Comment by ardref** [comment] 2022-02-18 20:21
It works now - thank you!
